### ISSUE TITLE
AttributeError: 'unicode object has no attribute 'zipWithIndex'

### ISSUE THREAD

**Issue by denisemauldin** [mcapuccini/spark-tutorial#2]
Hi,

I downloaded the latest version of Spark and installed it.  I'm using pyspark and when I open a pyspark console and attempt to follow the tutorial I get an error.

> > > tRdd = sc.textFile("dna.txt")
> > > tRdd.collect()
> > > [u'TGCTTTGATATCAGCATGTCTAGCTTTAGAATTCAGTTTAGTGCGCTGATCTGAGTCGAGATAAAATCACCAGTACCCAAAACCAGGCGGGCTCGCCACG', u'TTGGCTAATCCTGGTACATTTTGTAATCAATGTTCAGAAGAAAATTTGTGTTAGAAGGACGAGTCACCACGTACCAATAGCAACAACGATCGGTCGGACT', u'ATTCATTGTGGTGGTGACGCTCGGATTACACGGGAAAGGTGCTTGTGTCCCGACAGGCTAGGATATAATGCTGAGGCGTTACCCCAATCGTTCAGCGTGG', u'GATTTGCTACAACTTCTGAGTGCTACATGTACGAGACCATGTTATGTATGCACAAGGCCGACAATAGGACGTAGCCTTCGAGTTAGTACGTAGCGTGGTC', u'GCATAAGCACAGTAGATCCTCCCCGCGCATCCTATTTATTAAGTTAATTCTATAGCAATACGATCATATGCGGATGGGCAGTGGCCGGTAGTCACACGTC', u'TACCGCGGTGCTCAATGACCGGGACTAAAGAGGCGAAGATTATGGTGTGTGACCCGTTATGCTCGAGTTCGGTCAGAGCGTCATTGCGAGTAGTCGATTG', u'CTTTCTCAATCTCCGAGCGATTTAGCGTGACAGCCCCAGGGAACCCACAAAATGTGATCGCAGTCCATCCGATCGTACACAGAAAGGAAGGTCCCCATAC', u'ACCGACGCACCTGTTTACACGTCGTATGCATAAACGAGCCGCACGAACCAGAGAGCATAAAGAGGACCTCTAGTTCCTTTACAAAGTACAGGTTCGCCTG', u'TCGCCAAGATGCCTTACCTAGATGCAATGACGGACGTATTCCTCTGGCCTCAACGGTTCCTGCTTTCGCTGGGATCCAAGATTGGCAGCTGAAACCGCCT', u'TTCCAAAGTGAGTCCTTCGTCTGTGACTAACTGTGCCAAATCGTCTTGCAAACTCCTGATCCAGTTTAACTCACCAAATTATAGCCATACAGACCCAAAT']
> > > 
> > > s = tRdd.flatMap(lambda sequence: sequence.zipWithIndex().map(lambda res,pos: (res,pos)  ) )
> > > s.take(1)
> > > AttributeError: 'unicode' object has no attribute 'zipWithIndex'

Have I translated the Scala to Python incorrectly?  I seem to be getting this error on everything where I have a tuple or list of sequences ('tuple' object has no attribute 'zipWithIndex' or 'list' object has no attribute 'zipWithIndex').

Thanks,
Denise

**Comment by mcapuccini** [comment]
@denisemauldin  zipWithIndex belongs to the Scala API, you need to find the equivalent in Python
